// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CheckAvailableService.proto

package com.item.management.client.service;

public final class CheckAvailableServiceOuterClass {
  private CheckAvailableServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_item_management_client_service_CheckAvailableRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_item_management_client_service_CheckAvailableRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_item_management_client_service_CheckAvailableRequestResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_item_management_client_service_CheckAvailableRequestResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033CheckAvailableService.proto\022\"com.item." +
      "management.client.service\"[\n\025CheckAvaila" +
      "bleRequest\022\020\n\010officeId\030\001 \001(\t\022\016\n\006itemId\030\002" +
      " \001(\t\022\r\n\005total\030\003 \001(\005\022\021\n\trequestId\030\004 \001(\t\"j" +
      "\n\035CheckAvailableRequestResponse\022\021\n\treque" +
      "stId\030\001 \001(\t\022\020\n\010officeId\030\002 \001(\t\022\r\n\005total\030\003 " +
      "\001(\005\022\025\n\rserialNumbers\030\004 \003(\t2\241\001\n\025CheckAvai" +
      "lableService\022\207\001\n\007checkAR\0229.com.item.mana" +
      "gement.client.service.CheckAvailableRequ" +
      "est\032A.com.item.management.client.service",
      ".CheckAvailableRequestResponseB\002P\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_item_management_client_service_CheckAvailableRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_item_management_client_service_CheckAvailableRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_item_management_client_service_CheckAvailableRequest_descriptor,
        new java.lang.String[] { "OfficeId", "ItemId", "Total", "RequestId", });
    internal_static_com_item_management_client_service_CheckAvailableRequestResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_item_management_client_service_CheckAvailableRequestResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_item_management_client_service_CheckAvailableRequestResponse_descriptor,
        new java.lang.String[] { "RequestId", "OfficeId", "Total", "SerialNumbers", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
