// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UpdateStockService.proto

package com.item.management.client.service;

public interface UpdateStockRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.item.management.client.service.UpdateStockRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 type = 1;</code>
   */
  int getType();

  /**
   * <code>string officeId = 2;</code>
   */
  java.lang.String getOfficeId();
  /**
   * <code>string officeId = 2;</code>
   */
  com.google.protobuf.ByteString
      getOfficeIdBytes();

  /**
   * <code>repeated string serialNumbers = 3;</code>
   */
  java.util.List<java.lang.String>
      getSerialNumbersList();
  /**
   * <code>repeated string serialNumbers = 3;</code>
   */
  int getSerialNumbersCount();
  /**
   * <code>repeated string serialNumbers = 3;</code>
   */
  java.lang.String getSerialNumbers(int index);
  /**
   * <code>repeated string serialNumbers = 3;</code>
   */
  com.google.protobuf.ByteString
      getSerialNumbersBytes(int index);
}
