// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UpdateStockService.proto

package com.item.management.client.service;

public interface UpdateStockResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.item.management.client.service.UpdateStockResponse)
    com.google.protobuf.MessageOrBuilder {
}
