// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CheckAvailableService.proto

package com.item.management.client.service;

public interface CheckAvailableRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.item.management.client.service.CheckAvailableRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string officeId = 1;</code>
   */
  java.lang.String getOfficeId();
  /**
   * <code>string officeId = 1;</code>
   */
  com.google.protobuf.ByteString
      getOfficeIdBytes();

  /**
   * <code>string itemId = 2;</code>
   */
  java.lang.String getItemId();
  /**
   * <code>string itemId = 2;</code>
   */
  com.google.protobuf.ByteString
      getItemIdBytes();

  /**
   * <code>int32 total = 3;</code>
   */
  int getTotal();

  /**
   * <code>string requestId = 4;</code>
   */
  java.lang.String getRequestId();
  /**
   * <code>string requestId = 4;</code>
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();
}
