// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CheckAvailableService.proto

package com.item.management.client.service;

public interface CheckAvailableRequestResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.item.management.client.service.CheckAvailableRequestResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string requestId = 1;</code>
   */
  java.lang.String getRequestId();
  /**
   * <code>string requestId = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();

  /**
   * <code>string officeId = 2;</code>
   */
  java.lang.String getOfficeId();
  /**
   * <code>string officeId = 2;</code>
   */
  com.google.protobuf.ByteString
      getOfficeIdBytes();

  /**
   * <code>int32 total = 3;</code>
   */
  int getTotal();

  /**
   * <code>repeated string serialNumbers = 4;</code>
   */
  java.util.List<java.lang.String>
      getSerialNumbersList();
  /**
   * <code>repeated string serialNumbers = 4;</code>
   */
  int getSerialNumbersCount();
  /**
   * <code>repeated string serialNumbers = 4;</code>
   */
  java.lang.String getSerialNumbers(int index);
  /**
   * <code>repeated string serialNumbers = 4;</code>
   */
  com.google.protobuf.ByteString
      getSerialNumbersBytes(int index);
}
